// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzevbvhhevlldxstmtnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56ZXZidmhoZXZsbGR4c3RtdG5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjM3MDcsImV4cCI6MjA1OTQzOTcwN30.volp9dsGiH1HEQjdz5TFPgp2kqr3PVrzkvTitZc_oEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);